### ISSUE TITLE
Plugin do nagiosu concurrent_inst

### ISSUE THREAD

**Issue by semik** [CESNET/etlog#2]
Vytvor v bashi plugin do nagiosu ktery bude brat 3 parametry: realm, warning a critical treshold. Hodnota pro celkovy treshodl bude soucet vsech poctu /api/concurrent_inst. Hodilo by se ale aby to bylo omezeno 5min rozdilem aby tam nevyskakovaly incidenty mezi fs.cvut.cz a vscht.cz - obecne jakymikoli institucemi ktere jsou prilis blizko.

Poustet by se to melo z ermon.cesnet.cz (bud lokalne, pokud pujde povolit pristup) a nebo pres NRPE tam je ale problem s povolenim vzdalenych argumentu - pripadne vysvetlim osobne. 

Rad bych to zaradil do centralniho monitoringu a primel instituce dat institution.xml do poradku. Hloupe je ze to vyprudi i ty kteri sami maji vse OK, ale maji neporadneho souseda. Pokud by te napadlo jak to vylepsit budu rad.

Je to nice-to-have ficura.

https://nagios-plugins.org/doc/guidelines.html

**Comment by lager1** [comment]
Skript je pripraven podle pozadavku a dnesnich pripominek - https://github.com/CESNET/etlog/blob/master/scripts/nagios/concurrent_inst.sh.
